Dapper-a-simple-web-app/Models/Article.cs
using Dapper.Contrib.Extensions;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace Dapper_SimpleWebApp.Models
{
	[Table("article")]
	public class Article
	{
		public long Id { get; set; }
		public string Title { get; set; }
		public string Body { get; set; }
		public DateTime Date { get; set; }

		[Computed]
		public Author Author { get; set; }

		[Computed]
		public List<Tag> Tags { get; set; }

		[DisplayName("Author")]
		public int AuthorId { get; set; }

		public Article()
		{
			Date = DateTime.Now;
			Id = 0;
		}

		[Computed]
		public string TagsCSV {get;set;}

		public string TagsForDisplay()
		{
			if(Tags != null && Tags.Count > 0)
			{
				var csv = String.Join(", ", Tags.Select(tag => tag.Name).ToArray());
				return csv;
			}
			return "";
		}
	}
}

Dapper-a-simple-web-app/Models/ArticleModel.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Dapper_SimpleWebApp.Models
{
	public class Article
	{
		public int Id { get; set; }
		public string Title { get; set; }
		public string Body { get; set; }

		[DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}",ApplyFormatInEditMode = true)]
		public DateTime Date { get; set; }

		//[ResultColumn]
		//public Author Author { get; set; }

		[DisplayName("Author")]
		public int AuthorId { get; set; }

		//[ResultColumn]
		//public List<Tag> Tags { get; set; }

		public Article()
		{
			Date = DateTime.Now;
			Id = int.MinValue;
			//Tags = new List<Tag>();
		}
	}
}

Dapper-a-simple-web-app/Models/ArticleTag.cs
using Dapper.Contrib.Extensions;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Dapper_SimpleWebApp.Models
{
	[Table("articleTag")]
	public class ArticleTag
	{
		public long Id {get;set;}
		public long ArticleId { get; set; }
		public long TagId { get; set; }
		
		public ArticleTag()
		{
			Id = 0;
		}
	}
}

Dapper-a-simple-web-app/Models/Author.cs
using Dapper.Contrib.Extensions;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Dapper_SimpleWebApp.Models
{
	[Table("author")]
	public class Author
	{
		public long Id { get; set; }
		public string Name { get; set; }

		[Computed]
		public List<Article> Articles {get;set;}
		
		public Author()
		{
			Id = 0;
		}
	}
}

Dapper-a-simple-web-app/Models/Tag.cs
using Dapper.Contrib.Extensions;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Dapper_SimpleWebApp.Models
{
	[Table("tag")]
	public class Tag
	{
		public long Id { get; set; }
		public string Name { get; set; }

		[Computed]
		public int Count {get;set;}

		[Computed]
		public List<Article> Articles {get;set;}
		
		public Tag()
		{
			Id = 0;
		}
	}
}

Dapper-a-simple-web-app/Models/ViewModels/ArticleViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;

namespace Dapper_SimpleWebApp.Models
{
	public class ArticleViewModel
	{
		public Article Article { get; set; }
		public List<SelectListItem> Authors { get; set; }
		public List<Tag> AllTags {get;set;}
	}
}

Dapper-a-simple-web-app/Models/ViewModels/ErrorViewModel.cs
using System;

namespace Dapper_SimpleWebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Dapper-a-simple-web-app/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Dapper_SimpleWebApp.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Dapper_SimpleWebApp.Controllers
{
	public class ArticleController : Controller
	{
		private IArticleRepository _articleRepository;
		private IAuthorRepository _authorRepository;

		public ArticleController(IArticleRepository articleRepository, IAuthorRepository authorRepository)
		{
			_articleRepository = articleRepository;
			_authorRepository = authorRepository;
		}

		public IActionResult Index(int id)
		{
			var article = _articleRepository.RetrieveById(id);

			return View("Details", article);
		}

		public IActionResult Edit(int id)
		{
			var viewModel = new ArticleViewModel();
			var tagRepo = new TagRepository();

			viewModel.Article = _articleRepository.RetrieveById(id);
			if(viewModel.Article == null)
			{
				viewModel.Article = new Article();
			}
			var authors = _authorRepository.Fetch();
			viewModel.Authors = new List<SelectListItem>();
			foreach(var author in authors)
			{
				viewModel.Authors.Add(new SelectListItem(){Value=author.Id.ToString(), Text=author.Name});
			}
			viewModel.AllTags = tagRepo.FetchAll();

			return View(viewModel);
		}

		[HttpPost]
		public IActionResult Edit(Article article)
		{
			if(HttpContext.Request.Form.ContainsKey("delete"))
			{
				if(_articleRepository.Delete(article))
				{
					TempData["Message_Success"] = "Article was deleted";
					return RedirectToAction("List", "Article");
				}
			}
			else if(_articleRepository.Save(article))
			{
				TempData["Message_Success"] = "Article was saved";
			}

			return RedirectToAction("Edit", new {id=article.Id});
		}

		public IActionResult List()
		{
			var articles = _articleRepository.Fetch();

			return View(articles);
		}
	}
}

Dapper-a-simple-web-app/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Dapper_SimpleWebApp.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Dapper_SimpleWebApp.Controllers
{
	public class AuthorController : Controller
	{
		private IAuthorRepository _authorRepository;

		public AuthorController(IAuthorRepository authorRepository)
		{
			_authorRepository = authorRepository;
		}

		public IActionResult Details(int id)
		{
			var author = _authorRepository.RetrieveById(id);

			return View("Details", author);
		}

		public IActionResult Edit(int id)
		{
			var author = _authorRepository.RetrieveById(id);
			if(author == null)
			{
				author = new Author();
			}
			return View(author);
		}

		[HttpPost]
		public IActionResult Edit(Author author)
		{
			if(HttpContext.Request.Form.ContainsKey("delete"))
			{
				if(_authorRepository.Delete(author))
				{
					TempData["Message_Success"] = "Author was deleted";
					return RedirectToAction("List", "Author");
				}
			}
			else if(_authorRepository.Save(author))
			{
				TempData["Message_Success"] = "Author was saved";
			}

			return RedirectToAction("Edit", new {id=author.Id});
		}

		public IActionResult List()
		{
			var articles = _authorRepository.Fetch();

			return View(articles);
		}
	}
}

Dapper-a-simple-web-app/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Dapper_SimpleWebApp.Models;

namespace Dapper_SimpleWebApp.Controllers
{
	public class HomeController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Dapper-a-simple-web-app/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Dapper_SimpleWebApp.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Dapper_SimpleWebApp.Controllers
{
	public class TagController : Controller
	{
		private ITagRepository _tagRepository;
		private IArticleRepository _articleRepository;

		public TagController(ITagRepository tagRepository, IArticleRepository articleRepository)
		{
			_tagRepository = tagRepository;
			_articleRepository = articleRepository;
		}

		public IActionResult List()
		{
			var tags = _tagRepository.FetchAll();

			return View(tags);
		}

		public IActionResult Articles(int id)
		{
			var articles = _articleRepository.Fetch(tagId:id);

			return View("~/views/article/list.cshtml", articles);
		}
	}
}

Dapper-a-simple-web-app/Views/Article/Details.cshtml
@model Article
@{
	ViewData["Title"] = "Home Page";
}
<div class="row">
	<div class="col-xs-12">
		<h2>@Model.Title</h2>
		<p>
			By @Model.Author.Name on @Model.Date
		</p>
		<hr />
		<div style="">@Html.Raw(Model.Body)</div>
		<hr />
		@if(Model.Tags != null)
		{
			<span style="font-size:85%;">
				<span class="glyphicon glyphicon-tag"></span>
				<span>@Model.TagsForDisplay()</span>
			</span>
		}
	</div>
</div>

Dapper-a-simple-web-app/Views/Article/Edit.cshtml
@model ArticleViewModel
@{
	ViewData["Title"] = "Home Page";
}
<div class="row">
	<div class="col-xs-12">
		<h2>@Model.Article.Title</h2>
		<form method="POST" id="edit-article">
			<div class="form-group">
				<label for="title">Title</label>
				<input type="text" class="form-control" id="title" name="Article.Title" placeholder="Title" value="@Model.Article.Title">
			</div>
			<div class="form-group">
				<label for="authorId">Author</label>
				<select class="form-control" asp-for="@Model.Article.AuthorId" asp-items="@Model.Authors"></select> 
			</div>
			<div class="form-group">
				<label for="date">Date</label>
				<input type="text" id="Article.date" name="Article.date" class="form-control" value="@Model.Article.Date">
			</div>
			<div class="form-group">
				<label for="tags">Tags</label>
				<div id="tag-container">
					<input class="form-control" type="text" name="Article.TagsCSV" id="Article.TagsCSV" value="@Model.Article.TagsForDisplay()" placeholder="Separate tags with a comma" />
				</div>
			</div>
			<div class="form-group" style="clear:both;">
				<label for="body">Body</label>
				<textarea name="Article.Body" id="body" class="form-control" style="height:150px; display:none;"></textarea>
				<div id="summernote">@Html.Raw(Model.Article.Body)</div>
			</div>
			<input type="hidden" name="Article.id" value="@Model.Article.Id" />
			<button type="submit" class="btn btn-default">Submit</button>
			@if(Model.Article.Id > 0) {
			<button type="submit" name="delete" class="btn btn-danger">Delete</button>
			}
		</form>
	</div>
</div>

@section Head
{
}

@section Scripts
{
	<link href="/js/summernote/summernote.css" rel="stylesheet">
	<script src="/js/summernote/summernote.js"></script>
	<script>
	$(document).ready(function () {
		$("#summernote").summernote({height:200});
	});
	$("#edit-article").submit(function () {
		$("#body").val($("#summernote").summernote("code"));
		return true;
	});
	</script>
}

Dapper-a-simple-web-app/Views/Article/List.cshtml
@model List<Article>
@{
	ViewData["Title"] = "Home Page";
}

<div class="row">
	<div class="col-xs-12">
		<h2>Articles</h2>
		@if(Model.Count > 0) {
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Title</th>
					<th>Author</th>
					<th>Tags</th>
					<th>Published</th>
					<th>Id</th>
					<th></th>
				</tr>
			</thead>
			
			@foreach(var article in Model) {
			<tr>
				<td>
					@*<a asp-controller="Article" asp-action="" asp-all-route-data='@new Dictionary<string, string>{{"id", article.Id.ToString()}};'>@article.Title</a>*@
					<a href="/article/@article.Id">@article.Title</a>
				</td>
				<td>@article.Author.Name</td>
				<td>@article.TagsForDisplay()</td>
				<td>@article.Date</td>
				<td>@article.Id</td>
				<td>
					<a asp-controller="Article" asp-action="Edit" asp-all-route-data='@new Dictionary<string, string>{{"id", article.Id.ToString()}};'>Edit</a>
				</td>
			</tr>
			}
			<tr>
				<td colspan="99" style="padding-top:20px;"><a asp-controller="Article" asp-action="Edit"><span class="glyphicon glyphicon-plus"></span> Create new article</a></td>
			</tr>
		</table>
		} else {
			<p>There are no articles yet</p>
			<p>
				<a asp-controller="Article" asp-action="Edit"><span class="glyphicon glyphicon-plus"></span> Create new article</a>
			</p>
		}

	</div>
</div>

Dapper-a-simple-web-app/Views/Author/Details.cshtml
@model Author
@{
	ViewData["Title"] = "Home Page";
}
<div class="row">
	<div class="col-xs-12">
		<h2>@Model.Name</h2>

		@if(Model.Articles != null) {
		<p>All articles by @Model.Name</p>
		<ul>
			@foreach(var article in Model.Articles)
			{
				<li>
					<a href="/article/@article.Id">@article.Title</a>
				</li>
			}
		</ul>
		} else {
			<p>@Model.Name has written no articles yet.</p>
		}
	</div>
</div>

Dapper-a-simple-web-app/Views/Author/Edit.cshtml
@model Author
@{
	ViewData["Title"] = "Home Page";
}
<div class="row">
	<div class="col-xs-12">
		<h2>Edit</h2>
		<form method="POST">
			<div class="form-group">
				<label for="name">Name</label>
				<input type="text" class="form-control" id="name" name="name" placeholder="Name" value="@Model.Name">
			</div>
			<input type="hidden" name="id" value="@Model.Id" />
			<button type="submit" class="btn btn-default">Submit</button>

			@if(Model.Id > 0) {
			<button type="submit" name="delete" class="btn btn-danger">Delete</button>
			}
		</form>

	</div>
</div>

Dapper-a-simple-web-app/Views/Author/List.cshtml
@model List<Author>
@{
	ViewData["Title"] = "Home Page";
}
<div class="row">
	<div class="col-xs-12">
		<h2>Authors</h2>
		@if(Model.Count > 0) {
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Name</th>
					<th>Id</th>
					<th>Articles</th>
					<th></th>
				</tr>
			</thead>
			
			@foreach(var author in Model) {
			<tr>
				<td>
					<a asp-controller="Author" asp-action="Details" asp-all-route-data='@new Dictionary<string, string>{{"id", author.Id.ToString()}};'>@author.Name</a>
				</td>
				<td>@author.Id</td>
				<td>@if(author.Articles != null){<span>@author.Articles.Count</span>}else{<span>0</span>}</td>
				<td>
					<a asp-controller="Author" asp-action="Edit" asp-all-route-data='@new Dictionary<string, string>{{"id", author.Id.ToString()}};'>Edit</a>
				</td>
			</tr>
			}
			<tr>
				<td colspan="99" style="padding-top:20px;">
					<a asp-controller="Author" asp-action="Edit"><span class="glyphicon glyphicon-plus"></span> Create new author</a>
				</td>
			</tr>
		</table>
		} else {
			<p>There are no authors yet</p>
			<p>
				<a asp-controller="Author" asp-action="Edit"><span class="glyphicon glyphicon-plus"></span> Create new author</a>
			</p>
		}

	</div>
</div>

Dapper-a-simple-web-app/Views/Home/Index.cshtml
@{
	ViewData["Title"] = "Home Page";
}
<div class="row">
	<div class="col-xs-12">
		<h2>Dapper - A simple web app</h2>
		<p>
			A simple application to manage authors and their articles in an SQLite database using <a href="https://github.com/StackExchange/Dapper">Dapper</a>.
		</p>
		<ul>
			<li><a asp-area="" asp-controller="Article" asp-action="List">Articles</a></li>
			<li><a asp-area="" asp-controller="Author" asp-action="List">Authors</a></li>
			<li><a asp-area="" asp-controller="Tag" asp-action="List">Tags</a></li>
		</ul>
		<p>
			Authors have a one-to-many relationship with articles. Articles have a many-to-many relationship with tags via the <em>articleTag</em> and <em>tag</em> tables.
		</p>
		<p>
			Download <a href="http://sqlitebrowser.org/" >SQLite Browser</a> and look at the <em>app.db</em> database in the project root.
		</p>
		<h3>Database Schema</h3>
		<p>
			<img class="img-responsive" src="~/images/SQLite-db-schema.jpg" title="The database schema for this app's SQLite database" style="border:1px solid #ddd;" />
		</p>
	</div>
</div>

Dapper-a-simple-web-app/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Dapper - A simple web app</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
	<link rel="stylesheet" href="~/css/site.css" />
	@RenderSection("Head", required:false)
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div xclass="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li><a style="padding-left:0;" asp-controller="Home" asp-action="Index">Home</a></li>
					<li><a asp-controller="Article" asp-action="List">Articles</a></li>
					<li><a asp-controller="Author" asp-action="List">Authors</a></li>
					<li><a asp-controller="Tag" asp-action="List">Tags</a></li>
				</ul>
			</div>
		</div>
	</nav>
	<div class="container body-content">
		@if(TempData["Message_Success"] != null) {
			<div style="color:darkgreen; background-color:darkseagreen; font-weight:bold; padding:5px 15px; margin:10px 0;">@TempData["Message_Success"]</div>
		}
		@RenderBody()
		<hr />
		<footer>
			<p>&copy; 2017 - <a href="https://github.com/GarethElms/Dapper-a-simple-web-app">Dapper - A simple web app</a> by <a href="http://www.garethelms.org">Gareth Elms</a></p>
		</footer>
	</div>

	<script src="~/lib/jquery/dist/jquery.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>

	@RenderSection("Scripts", required:false)
</body>
</html>

Dapper-a-simple-web-app/Views/Tag/List.cshtml
@model List<Tag>
@{
	ViewData["Title"] = "Home Page";
}

<div class="row">
	<div class="col-xs-12">
		<h2>Tags</h2>
		@if(Model.Count > 0) {
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Tag</th>
					<th>Count</th>
				</tr>
			</thead>
			
			@foreach(var tag in Model) {
			<tr>
				<td>
					<a asp-controller="Tag" asp-action="articles" asp-all-route-data='@new Dictionary<string, string>{{"id", tag.Id.ToString()}};'>@tag.Name</a>
				</td>
				<td>@tag.Count</td>
			</tr>
			}
		</table>
		} else {
			<p>There are no tags yet</p>
		}

	</div>
</div>